# pull the official base image
FROM node:alpine
# set working direction
WORKDIR /app
# add `/app/node_modules/.bin` to $PATH
ENV PATH ../app/node_modules/.bin:$PATH
# install application dependencies
COPY ../app/package.json ./
COPY ../app/package-lock.json ./
RUN npm i
# add app
COPY . ./
# Run Command
ENTRYPOINT ["sh", "./entrypoint.sh"]

